// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

  @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
  tutorialSidebar: [
    {
      type: 'doc',
      label: 'Introducción',
      id: 'intro',
      className: 'intro',
    },
    {
      type: 'doc',
      label: 'Acceso',
      id: 'acceso/acceso',
      className: 'acceso-icono', 
    },
    {
      type: 'doc',
      label: 'Visión General',
      id: 'interfaz/interfaz',
      className: 'interfaz-icono',
    },
    {
      type: 'category',
      label: 'Paneles',
      link: { type: 'generated-index' },
      className: 'paneles-icono',
      items: [
        { type: 'doc', id: 'paneles/elements', className: 'elements-icono' },
        { type: 'doc', id: 'paneles/console', className: 'console-icono' },
        { type: 'doc', id: 'paneles/network', className: 'network-icono' },
        { type: 'doc', id: 'paneles/sources', className: 'sources-icono' },
        { type: 'doc', id: 'paneles/performance', className: 'performance-icono' },
        { type: 'doc', id: 'paneles/memory', className: 'memory-icono' },
        { type: 'doc', id: 'paneles/application', className: 'application-icono' },
        { type: 'doc', id: 'paneles/lighthouse', className: 'lighthouse-icono' },
      ],
    },
    {
      type: 'doc',
      label: 'Visión General',
      id: 'comandos',
      className: 'comandos-icono',
    },
  ],
};
module.exports = sidebars;